############################################################
# +------------------------------------------------------+ #
# |                 XJCraftAudit (Apply)                 | #
# +------------------------------------------------------+ #
############################################################
apply:
  enable: true
  command-block: WHITE_WOOL

accept-armorContent:
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  
spawn:
  world: MainLand
  x: 283
  y: 91
  z: -123
commandBlock:
  displayName: 回小镇的命令方块
  lore:
  - 放置后可传送回小镇
  - 然后建立基地-小镇的双向通道
  - 放置地点为基地的传送点，请选择方便来回的方位放置

signBlock:
  displayName: 回基地的牌子
  lore:
  - 请在小镇寻找一块篱笆围住的空地
  - 将木牌对着空命令方块放置并写上自己的名字
  - 来建立基地与小镇间的双向通道
  - 一次性使???
  - 当此牌子丢失时可用其他木牌代替
cmd-line: /tp @p[r=5] ${x} ${y} ${z}

nickname-prefix:
  op: '&c'
  applied: '&a'
  unapplied: '&f&o'
  enable: true
############################################################
# +------------------------------------------------------+ #
# |             XJCraftAudit (entitylimit)               | #
# +------------------------------------------------------+ #
############################################################
entityCheck:
  radius: 100
entityControl:
  autoClear: true
  interval: 1800
  radius: 100
  limit:
  - 1 = 10
  - 10 = 30
  - 20 = 0
  - 21 = 0
  - 50 = 0
  - 51 = 0
  - 52 = 0
  - 54 = 0
  - 55 = 0
  - 56 = 0
  - 57 = 0
  - 90 = 20
  - 92 = 20
  - 93 = 20
  - 94 = 20
  - 95 = 20
  - 96 = 40
  - 97 = 20
  - 98 = 20
  - 120 = 100
message:
  desc: 此插件限制只能玩家使用
  notExit: 不存在该玩家
  applySuccess: 恭喜你已经通过审核，请一次性完成通道的建立！你可以在群共享内找到小镇的示意图，包含了小镇空闲地皮的示意图
  applyFail: 抱歉，未通过审核，请继续努力
  applyDup: 你已经通过审核了，不必再申请?
  broadcast: <player> 通过了考核
  passageCompleted: 成功建立基地-小镇的双向通道
  passageOccupied: 此方块已经被占用，请寻找其他空方块
  baseNotExit: 基地不存在
  tip: 请保持背包有两个空位再申请考核